# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frabit < Formula
  desc "The next-gene database automatic platform"
  homepage "https://www.frabit.tech"
  version "2.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/frabits/frabit/releases/download/v2.2.1/frabit_2.2.1_darwin_arm64.tar.gz"
      sha256 "188781510e5bd62314940b4a2a1c77a2efbb076853849c2b9656beefad89a697"

      def install
        bin.install "frabit-admin"
        bin.install "frabit-agent"
        bin.install "frabit-server"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/frabits/frabit/releases/download/v2.2.1/frabit_2.2.1_darwin_amd64.tar.gz"
      sha256 "cd4c5c0b5776ad9e0c1bd966a28960dc05e5fd8062a0be59aa2f8673b7996c52"

      def install
        bin.install "frabit-admin"
        bin.install "frabit-agent"
        bin.install "frabit-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frabits/frabit/releases/download/v2.2.1/frabit_2.2.1_linux_arm64.tar.gz"
      sha256 "18f8714350128e55d39b28e46352b7caaf83980920a1f61aa8a0ee352147fef8"

      def install
        bin.install "frabit-admin"
        bin.install "frabit-agent"
        bin.install "frabit-server"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/frabits/frabit/releases/download/v2.2.1/frabit_2.2.1_linux_amd64.tar.gz"
      sha256 "5c55dac4d659997496c96b4f1da6662281b09c78a84028b6034595ab6ed3da8c"

      def install
        bin.install "frabit-admin"
        bin.install "frabit-agent"
        bin.install "frabit-server"
      end
    end
  end
end
