# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frabit < Formula
  desc "Frabit is a comprehensive open source database automatic platform."
  homepage "https://www.frabit.tech/"
  version "2.0.10"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/frabits/frabit/releases/download/v2.0.10/frabit_2.0.10_darwin_arm64.tar.gz"
      sha256 "44c0db3c11a880f6d572076cbdfcdf53de4ce05ce1a51af236e515441376721e"

      def install
        bin.install "frabit-admin"
        bin.install "frabit-agent"
        bin.install "frabit-server"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/frabits/frabit/releases/download/v2.0.10/frabit_2.0.10_darwin_amd64.tar.gz"
      sha256 "f24f764bac60defb3e1d827b4309e70a1c459f4d1e6ea882b6467470efd50930"

      def install
        bin.install "frabit-admin"
        bin.install "frabit-agent"
        bin.install "frabit-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/frabits/frabit/releases/download/v2.0.10/frabit_2.0.10_linux_amd64.tar.gz"
      sha256 "2e2aba258f784ef4cc5167b1a02fe2904e9dcfe7fe7781c653bcaee140687060"

      def install
        bin.install "frabit-admin"
        bin.install "frabit-agent"
        bin.install "frabit-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frabits/frabit/releases/download/v2.0.10/frabit_2.0.10_linux_arm64.tar.gz"
      sha256 "9efa1e8fe926cd69f12cd8bd732928410993c2afb606d39a88bb7784800e56cd"

      def install
        bin.install "frabit-admin"
        bin.install "frabit-agent"
        bin.install "frabit-server"
      end
    end
  end
end
