# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frabit < Formula
  desc "The next-generation database automatic operation platform"
  homepage "https://www.frabit.tech/"
  version "2.1.14"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/frabits/frabit/releases/download/v2.1.14/frabit_2.1.14_darwin_arm64.tar.gz"
      sha256 "739c964598eb01450bdeeb17cf9203f75c774eaab6da0121e8f077721f01f864"

      def install
        bin.install "frabit-admin"
        bin.install "frabit-agent"
        bin.install "frabit-server"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/frabits/frabit/releases/download/v2.1.14/frabit_2.1.14_darwin_amd64.tar.gz"
      sha256 "61ee6ceec2dd15890aceb2f4d78a622e6108f0ab2f3b8bbb32c7f1527e8803aa"

      def install
        bin.install "frabit-admin"
        bin.install "frabit-agent"
        bin.install "frabit-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frabits/frabit/releases/download/v2.1.14/frabit_2.1.14_linux_arm64.tar.gz"
      sha256 "75b70f0ab9a2151f685e16842933168797a4c0691f272aaaaf45db757416f2f1"

      def install
        bin.install "frabit-admin"
        bin.install "frabit-agent"
        bin.install "frabit-server"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/frabits/frabit/releases/download/v2.1.14/frabit_2.1.14_linux_amd64.tar.gz"
      sha256 "5d6279ee718fa708a7b99a93308cb6d6eea3ee1d7b47eee1dc15219a2ec44f30"

      def install
        bin.install "frabit-admin"
        bin.install "frabit-agent"
        bin.install "frabit-server"
      end
    end
  end
end
